### ISSUE TITLE
idx is a counter then a information leaker

### ISSUE THREAD

**Issue by peppelinux** [vcstuff/draft-looker-jwt-cwt-status-list#11]
Since idx is a positive integer number, it is assumed that its numbering is given by a counter
by guessing all the positive number greater than zero, an adversary would know how many credential a credential issuer has issued

would it be better using an exadecimal and opaque uid instead of a number?

**Comment by tplooker** [comment]
@peppelinux, an adversary looking at a status list only knows the maximum number of *possible* statuses that a list conveys, it cannot detect how many credentials have been issued by looking at the status list alone because issuers typically pre-allocate the list ahead of assigning a credential specific index in the list. Issuers can also employ certain noise techniques if they so choose by having "dead entries" in the list that are never assigned a credential.

**Comment by peppelinux** [comment]
it seems the answer that closes this issue

before doing that, and as an editorial strategy, I suggest to place your comment, even in a raw way, in the privacy consideration of the specs

that would take track of the FAQ directly in the specs

**Comment by paulbastian** [comment]
I agree. This probably belongs to the section 5.3 correlation risks and tracking as a counter measure

**Comment by paulbastian** [comment]
Close with #15 ?

**Comment by tplooker** [comment]
Agreed, closing.
